import pandas as pd

# df = pd.read_csv(
#     '/Users/edwardt/PycharmProjects/Upenn_Piazza/GS_Late/late_files/CIS_5150_Spring_2025_grades.csv')
#
# print(df.columns)

course_url = {

    "5420": 'https://gradescope.com/courses/929989/gradebook.csv',

}

canvas_id_map = {
    "5920": 1831659,


}

assignment_map = {
    "5500": {"Homework 1 - Submission Time": 12992073, "Homework 2 - Submission Time": 12992075,
             "Homework 3 - Submission Time": 12992077, "Homework 4 - Submission Time": 12992079,
             "Homework 5 - Submission Time": 12992081, "Homework 6 - Submission Time": 12992083},

    "5450": {
        "Homework 0 - Getting Started - Submission Time": 12991855,
        "Homework 1 - Submission - Submission Time": 12991857,
        "Homework 2 - Submission - Submission Time": 12991858,
        "Homework 3 - Submission - Submission Time": 12991859,
        "Homework 4 - Submission - Submission Time": 12991860,
        "Homework 5 - Submission - Submission Time": 12991861
    },
    "5470": {
        "Lab 1:  Introduction to Software Analysis - Submission Time": 1,
        "Lab 2: The LLVM Framework - Submission Time": 2,
        "Lab 3: Random Testing - Submission Time": 3,
        "Lab 4: Delta debugging - Submission Time": 4,
        "Lab 5: Statistical debugging - Submission Time": 5,
        "Lab 6: Dataflow analysis - Submission Time": 6,
        "Lab 7: Pointer analysis - Submission Time": 7,
        "Lab 8: Constraint-based analysis - Submission Time": 8
    },

    "5850": {
        "Homework 1 - Submission Time": 12294499,
        "Homework 2 - Submission Time": 12294500,
        "Homework 3 - Submission Time": 12294502,
        "Homework 5 - Submission Time": 12294504
    },

    "5210": {
        "Homework 1: Python Skills - Submission Time": 12991781,
        "Homework 2: Uninformed Search - Submission Time": 12991782,
        "Homework 3: Informed Search - Submission Time": 12991783,
        "Homework 4: Adversarial Games - Submission Time": 12991784,
        "Homework 5: Sudoku Games - Submission Time": 12991785,
        "Homework 6: MDP - Submission Time": 12991792,
        "Homework 7 : Reinforcement Learning - Submission Time": 12991786,
        "Homework 8 : Language Models - Submission Time": 12991787,
        "Homework 9: Perceptrons - Submission Time": 12991788,
        "Homework 10: Large Language Models - Submission Time": 12991789
    },
    "5150": {
        "Homework 1 - Submission Time": 12992048,
        "Homework 2 - Submission Time": 12992058,
        "Homework 3 - Submission Time": 12992060,
        "Homework 4 - Submission Time": 12992062,
        "Homework 5 - Submission Time": 12992064,
        "Homework 6 - Submission Time": 12992066,
        "Homework 7 - Submission Time": 12992068,
        "Homework 8 - Submission Time": 12992070,
        "Homework 9 - Submission Time": 12992072,
        "Homework 10 - Submission Time": 12992050,
        "Homework 11 - Submission Time": 12992052,
        "Homework 12 - Submission Time": 12992054,
        "Homework 13 - Submission Time": 12992056,
        "Project 1A: Drawing Bézier Curves - Submission Time": 12992076,
        "Project 1B: Drawing Cubic Bézier Spline Curves - Submission Time": 12992078,
        "Project 2A: Compression of Audio Signals Using Haar Wavelets - Submission Time": 12992080,
        "Project 2B: Compression of 2D Images Using Haar Wavelets - Submission Time": 12992082,
        "Project 3: Curve Interpolation - Submission Time": 12992084,
        "Project 4: Hard Margin SVM - Submission Time": 12992086,
        "Project 5: Ridge Regression - Submission Time": 12992088,

    },
    "5160": {
        "Module 1 Problem Set - Submission Time": 12793598,
        "Module 2 Problem Set - Submission Time": 12793594,
        "Module 3 Problem Set - Submission Time": 12919506,
        "Module 4 Problem Set - Submission Time": 12932828,
        "Module 6 Problem Set - Submission Time": 12978617,
        "Module 7 Problem Set - Submission Time": 13036366,
    },

    "5300": {
        "Homework 1: Intro to Regular Expressions and Tokenization - Submission Time": 12992263,
        "Homework 2: Text Classification - Submission Time": 12992264,
        "Homework 3: N-Gram Language Models - Submission Time": 12992265,
        "Homework 4: Vector Space Models - Submission Time": 12992266,
        "Homework 5: Advanced Vector Space Models - Submission Time": 12992267,
        "Homework 6 - Submission Time": 12992268,
        "Homework 7: Fine-tuning Pre-trained Language Models - Submission Time": 12992269,
        "Homework 8: Large Language Models & Prompting - Submission Time": 12992272,
        "Homework 9: Text Simplification as Machine Translation - Submission Time": 12992274

    },

    "5420": {
        'Homework 1 - Submission Time': 12992188,
        'Homework 2 - Submission Time': 12992191,
        'Homework 3 - Submission Time': 12992192,
        'Homework 4 - Submission Time': 12992193,
        'Homework 5 - Submission Time': 12992194,
        'Homework 6 - Submission Time': 12992195,
        'Homework 7 - Submission Time': 12992196,
        'Homework 8 - Submission Time': 12992197,
        'Homework 9 - Submission Time': 12992198,
        'Homework 10 - Submission Time': 12992189,
        'Homework 11 - Submission Time': 12992190},

    "5510": {
        'Homework 1 - Submission Time': 12470648,
        'Homework 2 - Submission Time': 12470649,
        'Homework 3 - Submission Time': 12470650,
        'Project 1 - Submission Time': 12470664,
        'Project 2 - Submission Time': 12470665,
        'Project 3 - Submission Time': 12470666},

    "5930": {
        "Assignment 02: Transistors to Logic - Submission Time": 12991311,
        "Assignment 03: Sequential Logic & Memory - Submission Time": 12991303,
        "Assignment 04: Datapath - Submission Time": 12991304,
        "Assignment 05: LC4 ISA - Submission Time": 12991313,
        "Assignment 06: LC4 Assembly Programming (Gradescope) - Submission Time": 12991315,
        "Assignment 07: LC4 Assembly and I/O (Gradescope) - Submission Time": 12991316,
        "Assignment 08: Connecting C to Assembly and I/O Devices - Submission Time": 12991319,
        "Assignment 09: Intro to C and its Development Environment - Submission Time": 12991321,
        "Assignment 10: Strings in C (Gradescope) - Submission Time": 12991310,
        "Assignment 11: File I/O, Making the LC4 Assembler - Submission Time": 12991328
    },
    "5940": {

        "Module 1 Programming Assignment and Submission - Submission Time": 12991406,
        "Module 2 Programming Assignment and Submission - Submission Time": 12991416,
        "Module 3 Programming Assignment and Submission - Submission Time": 12991418,

    },

    "5960": {"Module 1-2 Homework Assignment - Submission Time": 12991679,
             "Module 3-4 Homework Assignment - Submission Time": 12991689,
             "Module 5-6 Homework Assignment - Submission Time": 12991692,
             "Module 7-8 Homework Assignment - Submission Time": 12991695,
             "Module 9-10 Homework Assignment - Submission Time": 12991698,
             "Module 11-12 Homework Assignment - Submission Time": 12991682,
             "Module 13 Homework Assignment - Submission Time": 12991684},

    "5810": {"Homework 1 - Convolution - Submission Time": 12667482,
             "Homework 2 - Canny Edge Detection - Submission Time": 12667483,
             "Homework 3 - Optical Flow - Submission Time": 12667474,
             "Project 1 - Dolly Zoom - Submission Time": 12667502,
             "Project 2 - Canny Edge Detection - Submission Time": 12667503,
             "Project 3 - Laplacian Blending - Submission Time": 12667504,
             "Project 4 - Homography Estimation - Submission Time": 12667505,
             "Project 5 - Image Morphing - Submission Time": 12667506,
             "Project 6 - Poisson Image Editing - Submission Time": 12667507,
             "Project 7 - Linear Regression - Submission Time": 12667476,
             "Project 8 - Linear Perceptron - Submission Time": 12667508,
             "Project 9 - Classification Part 1 - Submission Time": 12667477,
             "Project 9 - Classification Part 2 - Submission Time": 12667509,
             },

    "5920": {"Module 1 Assignment - Submission Time": 12991250, "Module 2 Assignment - Submission Time": 12991260,
             "Module 3 Assignment - Submission Time": 12991262, "Module 4 Assignment - Submission Time": 12991264,
             "Module 5 Assignment - Submission Time": 12991246, "Module 6 Assignment - Submission Time": 12991267,
             "Module 7 Assignment - Submission Time": 12991269, "Module 8 Assignment - Submission Time": 12991271,
             "Module 9 Assignment - Submission Time": 12991273,
             "Module 10 Assignment - Submission Time": 12991252, "Module 11 Assignment - Submission Time": 12991254,
             "Module 12 Assignment - Submission Time": 12991256,
             "Module 13 Assignment - Submission Time": 12991258, },

    "5550": {'Homework 0 [HW0] - Submission Time': 12470562, 'Homework 1 [HW1] - Submission Time': 12470563,
             'Homework 2 [HW2] - Submission Time': 12470564, 'Homework 4 [HW4] - Submission Time': 12470566,
             'Homework 3 [HW3] - Submission Time': 12470565, 'Homework 5 [HW5] - Submission Time': 12470567,
             'Homework 6 [HW6] - Submission Time': 12470568, 'Homework 7 [HW7] - Submission Time': 12470569,
             'Homework 8 [HW8] - Submission Time': 12470570, 'Homework 9 [HW9] - Submission Time': 12470571,
             },
    "2400": {"Mod_03_HW - Submission Time": 11936752,
             "Mod_04_HW - Submission Time": 11936754,
             "Mod_05_HW - Submission Time": 11936756,
             "Mod_06_HW_Part1 - Submission Time": 11936757,
             "Mod_07_HW - Submission Time": 11936762,
             "Mod_08_HW - Submission Time": 11936764,
             "Mod_10_12_HW - Submission Time": 11936767,
             "Project1_Part1 - Submission Time": 11936770,
             "Project1_Part2 - Submission Time": 11936771,
             "Project2_Part1 - Submission Time": 11936774,
             "Project2_Part2_Autograder - Submission Time": 11936775,
             "Mod_09_HW-Part1 - Submission Time": 11936766,
             "Mod_09_HW-Part2 - Submission Time": 12143596,
             },
    "5460": {'HW1 Problem 1 Code - Submission Time': 12,
             'HW4 Problem 1 Code - Submission Time': 12,
             'HW1 Problem 3 Code - Submission Time': 12,
             'HW4 PDF Submission - Submission Time': 12,
             'HW0 Problem 4 Code - Submission Time': 12,
             'HW3 PDF Submission - Submission Time': 12,
             'HW2 Problem 3 Code - Submission Time': 12,
             'HW1 PDF Submission - Submission Time': 12,
             'HW2 PDF Submission - Submission Time': 12,
             'HW0 PDF Submission - Submission Time': 12,
             'HW3 Problem 4 Code - Submission Time': 12,
             'HW4 Problem 2 Code - Submission Time': 12,
             'HW4 Problem 3 Code - Submission Time': 12,

             }
}

filters = {"5500": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1 - Submission Time",
                    "Homework 1 - Lateness (H:M:S)",
                    "Homework 2 - Submission Time",
                    "Homework 2 - Lateness (H:M:S)",
                    "Homework 3 - Submission Time",
                    "Homework 3 - Lateness (H:M:S)",
                    "Homework 4 - Submission Time",
                    "Homework 4 - Lateness (H:M:S)",
                    "Homework 5 - Submission Time",
                    "Homework 5 - Lateness (H:M:S)",
                    "Homework 6 - Submission Time",
                    "Homework 6 - Lateness (H:M:S)"],
           "5450": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 0 - Getting Started - Submission Time",
                    "Homework 0 - Getting Started - Lateness (H:M:S)",
                    "Homework 1 - Submission - Submission Time",
                    "Homework 1 - Submission - Lateness (H:M:S)",
                    "Homework 2 - Submission - Submission Time",
                    "Homework 2 - Submission - Lateness (H:M:S)",
                    "Homework 3 - Submission - Submission Time",
                    "Homework 3 - Submission - Lateness (H:M:S)",
                    "Homework 4 - Submission - Submission Time",
                    "Homework 4 - Submission - Lateness (H:M:S)",
                    "Homework 5 - Submission - Submission Time",
                    "Homework 5 - Submission - Lateness (H:M:S)"

                    ],
           "5150": [
               "First Name", "Last Name", "Name", "SID", "Email", "Sections",
               "Homework 1 - Submission Time",
               "Homework 2 - Submission Time",
               "Homework 3 - Submission Time",
               "Homework 4 - Submission Time",
               "Homework 5 - Submission Time",
               "Homework 6 - Submission Time",
               "Homework 7 - Submission Time",
               "Homework 8 - Submission Time",
               "Homework 9 - Submission Time",
               "Homework 10 - Submission Time",
               "Homework 11 - Submission Time",
               "Homework 12 - Submission Time",
               "Homework 13 - Submission Time",

               "Homework 1 - Lateness (H:M:S)",
               "Homework 2 - Lateness (H:M:S)",
               "Homework 3 - Lateness (H:M:S)",
               "Homework 4 - Lateness (H:M:S)",
               "Homework 5 - Lateness (H:M:S)",
               "Homework 6 - Lateness (H:M:S)",
               "Homework 7 - Lateness (H:M:S)",
               "Homework 8 - Lateness (H:M:S)",
               "Homework 9 - Lateness (H:M:S)",
               "Homework 10 - Lateness (H:M:S)",
               "Homework 11 - Lateness (H:M:S)",
               "Homework 12 - Lateness (H:M:S)",
               "Homework 13 - Lateness (H:M:S)",

               "Project 1A: Drawing Bézier Curves - Submission Time",
               "Project 1B: Drawing Cubic Bézier Spline Curves - Submission Time",
               "Project 2A: Compression of Audio Signals Using Haar Wavelets - Submission Time",
               "Project 2B: Compression of 2D Images Using Haar Wavelets - Submission Time",
               "Project 3: Curve Interpolation - Submission Time",
               "Project 4: Hard Margin SVM - Submission Time",
               "Project 5: Ridge Regression - Submission Time",

               "Project 1A: Drawing Bézier Curves - Lateness (H:M:S)",
               "Project 1B: Drawing Cubic Bézier Spline Curves - Lateness (H:M:S)e",
               "Project 2A: Compression of Audio Signals Using Haar Wavelets - Lateness (H:M:S)",
               "Project 2B: Compression of 2D Images Using Haar Wavelets - Lateness (H:M:S)",
               "Project 3: Curve Interpolation - Lateness (H:M:S)",
               "Project 4: Hard Margin SVM - Lateness (H:M:S)",
               "Project 5: Ridge Regression - Lateness (H:M:S)",

           ],

           "5160": [
               "First Name", "Last Name", "Name", "SID", "Email", "Sections",
               "Module 1 Problem Set - Submission Time",
               "Module 2 Problem Set - Submission Time",
               "Module 3 Problem Set - Submission Time",
               "Module 4 Problem Set - Submission Time",
               "Module 6 Problem Set - Submission Time",
               "Module 7 Problem Set - Submission Time",

               "Module 1 Problem Set - Lateness (H:M:S)",
               "Module 2 Problem Set - Lateness (H:M:S)",
               "Module 3 Problem Set - Lateness (H:M:S)",
               "Module 4 Problem Set - Lateness (H:M:S)",
               "Module 6 Problem Set - Lateness (H:M:S)",
               "Module 7 Problem Set - Lateness (H:M:S)",
           ],
           "5470": [
               "First Name", "Last Name", "Name", "SID", "Email", "Sections",
               "Lab 1:  Introduction to Software Analysis - Submission Time",
               "Lab 2: The LLVM Framework - Submission Time",
               "Lab 3: Random Testing - Submission Time",
               "Lab 4: Delta debugging - Submission Time",
               "Lab 5: Statistical debugging - Submission Time",
               "Lab 6: Dataflow analysis - Submission Time",
               "Lab 7: Pointer analysis - Submission Time",
               "Lab 8: Constraint-based analysis - Submission Time",

               "Lab 1:  Introduction to Software Analysis - Lateness (H:M:S)",
               "Lab 2: The LLVM Framework - Lateness (H:M:S)",
               "Lab 3: Random Testing - Lateness (H:M:S)",
               "Lab 4: Delta debugging - Lateness (H:M:S)",
               "Lab 5: Statistical debugging - Lateness (H:M:S)",
               "Lab 6: Dataflow analysis - Lateness (H:M:S)",
               "Lab 7: Pointer analysis - Lateness (H:M:S)",
               "Lab 8: Constraint-based analysis - Lateness (H:M:S)",
           ],

           "5850": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1 - Submission Time",
                    "Homework 1 - Lateness (H:M:S)",
                    "Homework 2 - Submission Time",
                    "Homework 2 - Lateness (H:M:S)",
                    "Homework 3 - Submission Time",
                    "Homework 3 - Lateness (H:M:S)",
                    "Homework 5 - Submission Time",
                    "Homework 5 - Lateness (H:M:S)"

                    ],

           "5210": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",

                    "Homework 1: Python Skills - Submission Time",
                    "Homework 1: Python Skills - Lateness (H:M:S)",
                    "Homework 2: Uninformed Search - Submission Time",
                    "Homework 2: Uninformed Search - Lateness (H:M:S)",
                    "Homework 3: Informed Search - Submission Time",
                    "Homework 3: Informed Search - Lateness (H:M:S)",
                    "Homework 4: Adversarial Games - Submission Time",
                    "Homework 4: Adversarial Games - Lateness (H:M:S)",
                    "Homework 5: Sudoku Games - Submission Time",
                    "Homework 5: Sudoku Games - Lateness (H:M:S)",
                    "Homework 6: MDP - Submission Time",
                    "Homework 6: MDP - Lateness (H:M:S)",
                    "Homework 7 : Reinforcement Learning - Submission Time",
                    # "Homework 7: Reinforcement Learning - Submission Time",
                    "Homework 7 : Reinforcement Learning - Lateness (H:M:S)",
                    "Homework 8 : Language Models - Submission Time",
                    "Homework 8 : Language Models - Lateness (H:M:S)",
                    "Homework 9: Perceptrons - Submission Time",
                    "Homework 9: Perceptrons - Lateness (H:M:S)",
                    "Homework 10: Large Language Models - Submission Time",
                    "Homework 10: Large Language Models - Lateness (H:M:S)",
                    ],
           "5300": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1: Intro to Regular Expressions and Tokenization - Submission Time",
                    "Homework 1: Intro to Regular Expressions and Tokenization - Lateness (H:M:S)",
                    "Homework 2: Text Classification - Submission Time",
                    "Homework 2: Text Classification - Lateness (H:M:S)",
                    "Homework 3: N-Gram Language Models - Submission Time",
                    "Homework 3: N-Gram Language Models - Lateness (H:M:S)",
                    "Homework 4: Vector Space Models - Submission Time",
                    "Homework 4: Vector Space Models - Lateness (H:M:S)",
                    "Homework 5: Advanced Vector Space Models - Submission Time",
                    "Homework 5: Advanced Vector Space Models - Lateness (H:M:S)",
                    "Homework 6 - Submission Time",
                    "Homework 6 - Lateness (H:M:S)",
                    "Homework 7: Fine-tuning Pre-trained Language Models - Submission Time",
                    "Homework 7: Fine-tuning Pre-trained Language Models - Lateness (H:M:S)",
                    "Homework 8: Large Language Models & Prompting - Submission Time",
                    "Homework 8: Large Language Models & Prompting - Lateness (H:M:S)",
                    "Homework 9: Text Simplification as Machine Translation - Submission Time",
                    "Homework 9: Text Simplification as Machine Translation - Lateness (H:M:S)",

                    ],
           "5420": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1 - Submission Time",
                    "Homework 1 - Lateness (H:M:S)",
                    "Homework 2 - Submission Time",
                    "Homework 2 - Lateness (H:M:S)",
                    "Homework 3 - Submission Time",
                    "Homework 3 - Lateness (H:M:S)",
                    "Homework 4 - Submission Time",
                    "Homework 4 - Lateness (H:M:S)",
                    "Homework 5 - Submission Time",
                    "Homework 5 - Lateness (H:M:S)",
                    "Homework 6 - Submission Time",
                    "Homework 6 - Lateness (H:M:S)",
                    "Homework 7 - Submission Time",
                    "Homework 7 - Lateness (H:M:S)",
                    "Homework 8 - Submission Time",
                    "Homework 8 - Lateness (H:M:S)",
                    "Homework 9 - Submission Time",
                    "Homework 9 - Lateness (H:M:S)",
                    "Homework 10 - Submission Time",
                    "Homework 10 - Lateness (H:M:S)",
                    "Homework 11 - Submission Time",
                    "Homework 11 - Lateness (H:M:S)"

                    ],
           "5510": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1 - Submission Time",
                    "Homework 1 - Lateness (H:M:S)",
                    "Homework 2 - Submission Time",
                    "Homework 2 - Lateness (H:M:S)",
                    "Homework 3 - Submission Time",
                    "Homework 3 - Lateness (H:M:S)",
                    "Project 1 - Submission Time",
                    "Project 1 - Lateness (H:M:S)",
                    "Project 2 - Submission Time",
                    "Project 2 - Lateness (H:M:S)",
                    "Project 3 - Submission Time",
                    "Project 3 - Lateness (H:M:S)"
                    ],

           "5810": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    'Homework 1 - Convolution - Submission Time',
                    'Homework 1 - Convolution - Lateness (H:M:S)',
                    'Homework 2 - Canny Edge Detection - Submission Time',
                    'Homework 2 - Canny Edge Detection - Lateness (H:M:S)',
                    'Homework 3 - Optical Flow - Submission Time',
                    'Homework 3 - Optical Flow - Lateness (H:M:S)',
                    "Project 1 - Dolly Zoom - Submission Time",
                    "Project 1 - Dolly Zoom - Lateness (H:M:S)",
                    'Project 2 - Canny Edge Detection - Submission Time',
                    'Project 2 - Canny Edge Detection - Lateness (H:M:S)',
                    'Project 3 - Laplacian Blending - Submission Time',
                    'Project 3 - Laplacian Blending - Lateness (H:M:S)',
                    'Project 4 - Homography Estimation - Submission Time',
                    'Project 4 - Homography Estimation - Lateness (H:M:S)',
                    'Project 5 - Image Morphing - Submission Time',
                    'Project 5 - Image Morphing - Lateness (H:M:S)',
                    'Project 6 - Poisson Image Editing - Submission Time',
                    'Project 6 - Poisson Image Editing - Lateness (H:M:S)',
                    'Project 7 - Linear Regression - Submission Time',
                    'Project 7 - Linear Regression - Lateness (H:M:S)',
                    'Project 8 - Linear Perceptron - Submission Time',
                    'Project 8 - Linear Perceptron - Lateness (H:M:S)',
                    'Project 9 - Classification Part 1 - Submission Time',
                    'Project 9 - Classification Part 1 - Lateness (H:M:S)',
                    'Project 9 - Classification Part 2 - Submission Time',
                    'Project 9 - Classification Part 2 - Lateness (H:M:S)',

                    ],

           "5930": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Assignment 02: Transistors to Logic - Submission Time",
                    "Assignment 02: Transistors to Logic - Lateness (H:M:S)",
                    "Assignment 03: Sequential Logic & Memory - Submission Time",
                    "Assignment 03: Sequential Logic & Memory - Lateness (H:M:S)",
                    "Assignment 04: Datapath - Submission Time",
                    "Assignment 04: Datapath - Lateness (H:M:S)",
                    "Assignment 05: LC4 ISA - Submission Time",
                    "Assignment 05: LC4 ISA - Lateness (H:M:S)",
                    "Assignment 06: LC4 Assembly Programming (Gradescope) - Submission Time",
                    "Assignment 06: LC4 Assembly Programming (Gradescope) - Lateness (H:M:S)",
                    "Assignment 07: LC4 Assembly and I/O (Gradescope) - Submission Time",
                    "Assignment 07: LC4 Assembly and I/O (Gradescope) - Lateness (H:M:S)",
                    "Assignment 08: Connecting C to Assembly and I/O Devices - Submission Time",
                    "Assignment 08: Connecting C to Assembly and I/O Devices - Lateness (H:M:S)",
                    "Assignment 09: Intro to C and its Development Environment - Submission Time",
                    "Assignment 09: Intro to C and its Development Environment - Lateness (H:M:S)",
                    "Assignment 10: File I/O, Making the LC4 Assembler - Submission Time",
                    "Assignment 10: File I/O, Making the LC4 Assembler - Lateness (H:M:S)",
                    "Assignment 10: Strings in C (Gradescope) - Submission Time",
                    "Assignment 10: Strings in C (Gradescope) - Lateness (H:M:S)",
                    "Assignment 11: File I/O, Making the LC4 Assembler - Submission Time",
                    "Assignment 11: File I/O, Making the LC4 Assembler - Lateness (H:M:S)"
                    ],

           "5940": [
               "First Name", "Last Name", "Name", "SID", "Email", "Sections",
               "Module 1 Programming Assignment and Submission - Submission Time",
               "Module 2 Programming Assignment and Submission - Submission Time",
               "Module 3 Programming Assignment and Submission - Submission Time",

               "Module 1 Programming Assignment and Submission - Lateness (H:M:S)",
               "Module 2 Programming Assignment and Submission - Lateness (H:M:S)",
               "Module 3 Programming Assignment and Submission - Lateness (H:M:S)",

           ],
           "5920": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Module 1 Assignment - Submission Time", 'Module 1 Assignment - Lateness (H:M:S)',
                    'Module 2 Assignment - Submission Time', 'Module 2 Assignment - Lateness (H:M:S)',
                    'Module 3 Assignment - Submission Time', 'Module 3 Assignment - Lateness (H:M:S)',
                    'Module 4 Assignment - Submission Time', 'Module 4 Assignment - Lateness (H:M:S)',
                    'Module 5 Assignment - Submission Time', 'Module 5 Assignment - Lateness (H:M:S)',
                    'Module 6 Assignment - Submission Time', 'Module 6 Assignment - Lateness (H:M:S)',
                    'Module 7 Assignment - Submission Time', 'Module 7 Assignment - Lateness (H:M:S)',
                    'Module 8 Assignment - Submission Time', 'Module 8 Assignment - Lateness (H:M:S)',
                    'Module 9 Assignment - Submission Time', 'Module 9 Assignment - Lateness (H:M:S)',
                    'Module 10 Assignment - Submission Time', 'Module 10 Assignment - Lateness (H:M:S)',
                    'Module 11 Assignment - Submission Time', 'Module 11 Assignment - Lateness (H:M:S)',
                    'Module 12 Assignment - Submission Time', 'Module 12 Assignment - Lateness (H:M:S)',
                    'Module 13 Assignment - Submission Time', 'Module 13 Assignment - Lateness (H:M:S)',
                    'Module 14 Assignment - Submission Time', 'Module 14 Assignment - Lateness (H:M:S)',

                    ],
           "5960": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    'Module 1-2 Homework Assignment - Submission Time',
                    'Module 1-2 Homework Assignment - Lateness (H:M:S)',
                    'Module 3-4 Homework Assignment - Submission Time',
                    'Module 3-4 Homework Assignment - Lateness (H:M:S)',
                    'Module 5-6 Homework Assignment - Submission Time',
                    'Module 5-6 Homework Assignment - Lateness (H:M:S)',
                    'Module 7-8 Homework Assignment - Submission Time',
                    'Module 7-8 Homework Assignment - Lateness (H:M:S)',
                    'Module 9-10 Homework Assignment - Submission Time',
                    'Module 9-10 Homework Assignment - Lateness (H:M:S)',
                    'Module 11-12 Homework Assignment - Submission Time',
                    'Module 11-12 Homework Assignment - Lateness (H:M:S)',
                    'Module 13-14 Homework Assignment - Submission Time',
                    'Module 13 Homework Assignment - Lateness (H:M:S)'],

           "5550": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    'Homework 0 [HW0] - Lateness (H:M:S)',
                    'Homework 0 [HW0] - Submission Time', 'Homework 1 [HW1] - Submission Time',
                    'Homework 2 [HW2] - Submission Time', 'Homework 4 [HW4] - Submission Time',
                    'Homework 6 [HW6] - Submission Time', 'Homework 7 [HW7] - Submission Time',
                    'Homework 8 [HW8] - Submission Time', 'Homework 3 [HW3] - Submission Time',
                    'Homework 3 [HW3] - Lateness (H:M:S)', 'Homework 9 [HW9] - Submission Time',
                    'Homework 9 [HW9] - Lateness (H:M:S)', 'Homework 5 [HW5] - Submission Time',
                    'Homework 5 [HW5] - Lateness (H:M:S)', 'Homework 0 [HW0] - Lateness (H:M:S)',
                    'Homework 1 [HW1] - Lateness (H:M:S)', 'Homework 2 [HW2] - Lateness (H:M:S)',
                    'Homework 4 [HW4] - Lateness (H:M:S)', 'Homework 6 [HW6] - Lateness (H:M:S)',
                    'Homework 8 [HW8] - Lateness (H:M:S)', 'Homework 7 [HW7] - Lateness (H:M:S)',
                    ],
           "2400": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Mod_03_HW - Submission Time",
                    'Mod_03_HW - Lateness (H:M:S)',
                    'Mod_04_HW - Submission Time', 'Mod_04_HW - Lateness (H:M:S)',
                    'Mod_05_HW - Submission Time',
                    'Mod_05_HW - Lateness (H:M:S)', 'Mod_06_HW_Part1 - Submission Time',
                    'Mod_06_HW_Part1 - Lateness (H:M:S)', 'Mod_07_HW - Submission Time',
                    'Mod_07_HW - Lateness (H:M:S)',
                    'Mod_08_HW - Submission Time', 'Mod_08_HW - Lateness (H:M:S)',
                    'Mod_09_HW-Part1 - Submission Time',
                    'Mod_09_HW-Part1 - Lateness (H:M:S)', 'Mod_09_HW-Part2 - Submission Time',
                    'Mod_09_HW-Part2 - Lateness (H:M:S)', 'Mod_10_12_HW - Submission Time',
                    'Mod_10_12_HW - Lateness (H:M:S)', 'Project1_Part1 - Submission Time',
                    'Project1_Part1 - Lateness (H:M:S)', 'Project1_Part2 - Submission Time',
                    'Project1_Part2 - Lateness (H:M:S)', 'Project2_Part1 - Submission Time',
                    'Project2_Part1 - Lateness (H:M:S)',
                    'Project2_Part2_Autograder - Submission Time',
                    'Project2_Part2_Autograder - Lateness (H:M:S)',
                    ],
           "5460": ['First Name', 'Last Name', "Name", 'SID', 'Email', 'Sections',

                    'HW1 Problem 1 Code - Submission Time',
                    'HW1 Problem 1 Code - Lateness (H:M:S)',

                    'HW4 Problem 1 Code - Submission Time',
                    'HW4 Problem 1 Code - Lateness (H:M:S)',

                    'HW1 Problem 3 Code - Submission Time',
                    'HW1 Problem 3 Code - Lateness (H:M:S)',

                    'HW4 PDF Submission - Submission Time',
                    'HW4 PDF Submission - Lateness (H:M:S)',

                    'HW0 Problem 4 Code - Submission Time',
                    'HW0 Problem 4 Code - Lateness (H:M:S)',

                    'HW3 PDF Submission - Submission Time',
                    'HW3 PDF Submission - Lateness (H:M:S)',

                    'HW2 Problem 3 Code - Submission Time',
                    'HW2 Problem 3 Code - Lateness (H:M:S)',

                    'HW1 PDF Submission - Submission Time',
                    'HW1 PDF Submission - Lateness (H:M:S)',

                    'HW2 PDF Submission - Submission Time',
                    'HW2 PDF Submission - Lateness (H:M:S)',

                    'HW0 PDF Submission - Submission Time',
                    'HW0 PDF Submission - Lateness (H:M:S)',

                    'HW3 Problem 4 Code - Submission Time',
                    'HW3 Problem 4 Code - Lateness (H:M:S)',

                    'HW4 Problem 2 Code - Submission Time',
                    'HW4 Problem 2 Code - Lateness (H:M:S)',

                    'HW4 Problem 3 Code - Submission Time',
                    'HW4 Problem 3 Code - Lateness (H:M:S)', ],

           }
